#==============================================================#
# 320 pg_archiver
#==============================================================#
pg_archiver:
  name: pg_archiver
  desc: PostgreSQL archiver process statistics
  query: |-
    WITH spl AS (SELECT archived_count,failed_count,last_archived_time,last_failed_time,stats_reset,
      ('x'||substr(last_archived_wal,1 ,8))::bit(32)::bigint AS finish_wal_high,
      ('x'||substr(last_archived_wal,9 ,8))::bit(32)::bigint AS finish_wal_mid,
      ('x'||substr(last_archived_wal,17,8))::bit(32)::bigint AS finish_wal_low,
      ('x'||substr(last_failed_wal,1 ,8))::bit(32)::bigint   AS failed_wal_high,
      ('x'||substr(last_failed_wal,9 ,8))::bit(32)::bigint   AS failed_wal_mid,
      ('x'||substr(last_failed_wal,17,8))::bit(32)::bigint   AS failed_wal_low
      FROM pg_stat_archiver
    ) SELECT
      archived_count AS finish_count,
      finish_wal_high, finish_wal_mid, finish_wal_low,
      extract(epoch FROM last_archived_time) AS finish_time,
      failed_count,
      failed_wal_high, failed_wal_mid, failed_wal_low,
      extract(epoch FROM last_failed_time)   AS failed_time,
      extract(epoch FROM stats_reset)        AS reset_time
    FROM spl;

  ttl: 60
  min_version: 090400
  tags: [ cluster ]
  metrics:
    - finish_count:        { usage: COUNTER ,description: Number of WAL files that have been successfully archived }
    - finish_wal_high:     { usage: GAUGE   ,description: High part (timeline) of the last successful archive wal filename }
    - finish_wal_mid:      { usage: GAUGE   ,description: Middle part (high32 of lsn) of the last successful archive wal filename }
    - finish_wal_low:      { usage: GAUGE   ,description: Low part (file count) of the last successful archive wal filename }
    - finish_time:         { usage: GAUGE   ,description: Time of the last successful archive operation }
    - failed_count:        { usage: COUNTER ,description: Number of failed attempts for archiving WAL files }
    - failed_wal_high:     { usage: GAUGE   ,description: High part (timeline) of the last failed archive wal filename }
    - failed_wal_mid:      { usage: GAUGE   ,description: Middle part (high32 of lsn) of the last failed archive wal filename }
    - failed_wal_low:      { usage: GAUGE   ,description: Low part (file count) of the last failed archive wal filename }
    - failed_time:         { usage: GAUGE   ,description: Time of the last failed archival operation }
    - reset_time:          { usage: GAUGE   ,description: Time at which archive statistics were last reset }


