##
# SYNNOPSIS
#       pg_sync_standby_*
#
# DESCRIPTION
#       PostgreSQL synchronous standby status and names
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90400 ~ higher
#       Source     220-pg_sync_standby.yml
#
# METRICS
#       names (LABEL)
#           List of standby servers that can support synchronous replication, <null> if not enabled
#       enabled (GAUGE)
#           Synchronous commit enabled, 1 if enabled, 0 if disabled
#
pg_sync_standby:
    name: pg_sync_standby
    desc: PostgreSQL synchronous standby status and names
    query: |
        SELECT CASE WHEN names <> '' THEN names ELSE '<null>' END AS names, CASE WHEN names <> '' THEN 1 ELSE 0 END AS enabled FROM (SELECT current_setting('synchronous_standby_names') AS names) n;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 90400
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - names:
            name: names
            usage: LABEL
            description: List of standby servers that can support synchronous replication, <null> if not enabled
        - enabled:
            name: enabled
            usage: GAUGE
            description: Synchronous commit enabled, 1 if enabled, 0 if disabled


