##
# SYNNOPSIS
#       pg_downstream_*
#
# DESCRIPTION
#       PostgreSQL replication client count group by state
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90400 ~ higher
#       Source     230-pg_downstrem.yml
#
# METRICS
#       state (LABEL)
#           Replication client state, could be one of startup|catchup|streaming|backup|stopping
#       count (GAUGE)
#           Count of corresponding state
#
pg_downstream:
    name: pg_downstream
    desc: PostgreSQL replication client count group by state
    query: |
        SELECT l.state, coalesce(count, 0 ) AS count FROM unnest(ARRAY ['streaming','startup','catchup', 'backup', 'stopping']) l(state) LEFT JOIN (SELECT state, count(*) AS count FROM pg_stat_replication GROUP BY state)r ON l.state =  r.state;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 90400
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - state:
            name: state
            usage: LABEL
            description: Replication client state, could be one of startup|catchup|streaming|backup|stopping
        - count:
            name: count
            usage: GAUGE
            description: Count of corresponding state


