##
# SYNNOPSIS
#       pg_slot.pg_slot_14_*
#
# DESCRIPTION
#       PostgreSQL replication slot metrics v14 with wal safe size and status
#
# OPTIONS
#       Tags       [cluster, primary]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    140000 ~ higher
#       Source     240-pg_slot.yml
#
# METRICS
#       slot_name (LABEL)
#           A unique, cluster-wide identifier for the replication slot
#       datname (LABEL)
#           The name of the database this slot is associated with, or null for physical slot.
#       active (GAUGE)
#           True(1) if this slot is currently actively being used
#       temporary (GAUGE)
#           True(1) if this is a temporary replication slot.
#       xmin (COUNTER)
#           The oldest transaction that this slot needs the database to retain.
#       catalog_xmin (COUNTER)
#           The oldest transaction affecting the system catalogs that this slot needs the database to retain.
#       restart_lsn (COUNTER)
#           The address (LSN) of oldest WAL which still might be required by the consumer of this slot
#       confirm_lsn (COUNTER)
#           The address (LSN) up to which the logical slot's consumer has confirmed receiving data.
#       retained_bytes (GAUGE)
#           Size of bytes that retained for this slot
#       safe_wal_size (GAUGE)
#           bytes that can be written to WAL which will not make slot into lost
#       wal_status (GAUGE)
#           WAL reserve status 0-3 means reserved,extended,unreserved,lost, -1 means other
#       spill_txns (COUNTER)
#           Xacts that spilled to disk due to logical decode mem exceeding (subtrans included)
#       spill_count (COUNTER)
#           Xacts that spilled to disk due to logical decode mem exceeding (a xact can be spilled multiple times)
#       spill_bytes (COUNTER)
#           Bytes that spilled to disk due to logical decode mem exceeding
#       stream_txns (COUNTER)
#           Xacts that streamed to decoding output plugin after mem exceed
#       stream_count (COUNTER)
#           Xacts that streamed to decoding output plugin after mem exceed  (a xact can be streamed multiple times)
#       stream_bytes (COUNTER)
#           Bytes that streamed to decoding output plugin after mem exceed
#       total_txns (COUNTER)
#           Number of decoded xacts sent to the decoding output plugin for this slot
#       total_bytes (COUNTER)
#           Number of decoded bytes sent to the decoding output plugin for this slot
#       reset_time (COUNTER)
#           When statistics were last reset
#
pg_slot_14:
    name: pg_slot
    desc: PostgreSQL replication slot metrics v14 with wal safe size and status
    query: |
        SELECT s.slot_name, database AS datname,active,temporary,xmin::TEXT::BIGINT AS xmin,catalog_xmin::TEXT::BIGINT  AS catalog_xmin,
          restart_lsn - '0/0' AS restart_lsn, confirmed_flush_lsn - '0/0' AS confirm_lsn,
          CASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retained_bytes,
          safe_wal_size, CASE wal_status WHEN 'reserved' THEN 0 WHEN 'extended' THEN 1 WHEN 'unreserved' THEN 2 WHEN 'lost' THEN 3 ELSE -1 END AS wal_status,
          spill_txns,spill_count,spill_bytes,stream_txns,stream_count,stream_bytes,total_txns,total_bytes,extract(EPOCH FROM now() - stats_reset) AS reset_time
        FROM pg_replication_slots s LEFT OUTER JOIN pg_stat_replication_slots ss ON s.slot_name = ss.slot_name;
    tags:
        - cluster
        - primary
    ttl: 10
    timeout: 0.1
    min_version: 140000
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - slot_name:
            name: slot_name
            usage: LABEL
            description: A unique, cluster-wide identifier for the replication slot
        - datname:
            name: datname
            usage: LABEL
            description: The name of the database this slot is associated with, or null for physical slot.
        - active:
            name: active
            usage: GAUGE
            description: True(1) if this slot is currently actively being used
        - temporary:
            name: temporary
            usage: GAUGE
            description: True(1) if this is a temporary replication slot.
        - xmin:
            name: xmin
            usage: COUNTER
            description: The oldest transaction that this slot needs the database to retain.
        - catalog_xmin:
            name: catalog_xmin
            usage: COUNTER
            description: The oldest transaction affecting the system catalogs that this slot needs the database to retain.
        - restart_lsn:
            name: restart_lsn
            usage: COUNTER
            description: The address (LSN) of oldest WAL which still might be required by the consumer of this slot
        - confirm_lsn:
            name: confirm_lsn
            usage: COUNTER
            description: The address (LSN) up to which the logical slot's consumer has confirmed receiving data.
        - retained_bytes:
            name: retained_bytes
            usage: GAUGE
            description: Size of bytes that retained for this slot
        - safe_wal_size:
            name: safe_wal_size
            usage: GAUGE
            description: bytes that can be written to WAL which will not make slot into lost
        - wal_status:
            name: wal_status
            usage: GAUGE
            description: WAL reserve status 0-3 means reserved,extended,unreserved,lost, -1 means other
        - spill_txns:
            name: spill_txns
            usage: COUNTER
            description: Xacts that spilled to disk due to logical decode mem exceeding (subtrans included)
        - spill_count:
            name: spill_count
            usage: COUNTER
            description: Xacts that spilled to disk due to logical decode mem exceeding (a xact can be spilled multiple times)
        - spill_bytes:
            name: spill_bytes
            usage: COUNTER
            description: Bytes that spilled to disk due to logical decode mem exceeding
        - stream_txns:
            name: stream_txns
            usage: COUNTER
            description: Xacts that streamed to decoding output plugin after mem exceed
        - stream_count:
            name: stream_count
            usage: COUNTER
            description: Xacts that streamed to decoding output plugin after mem exceed  (a xact can be streamed multiple times)
        - stream_bytes:
            name: stream_bytes
            usage: COUNTER
            description: Bytes that streamed to decoding output plugin after mem exceed
        - total_txns:
            name: total_txns
            usage: COUNTER
            description: Number of decoded xacts sent to the decoding output plugin for this slot
        - total_bytes:
            name: total_bytes
            usage: COUNTER
            description: Number of decoded bytes sent to the decoding output plugin for this slot
        - reset_time:
            name: reset_time
            usage: COUNTER
            description: When statistics were last reset

##
# SYNNOPSIS
#       pg_slot.pg_slot_13_*
#
# DESCRIPTION
#       PostgreSQL replication slot metrics v13 (wal safe size and status)
#
# OPTIONS
#       Tags       [cluster, primary]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    130000 ~ 140000
#       Source     240-pg_slot.yml
#
# METRICS
#       slot_name (LABEL)
#           A unique, cluster-wide identifier for the replication slot
#       datname (LABEL)
#           The name of the database this slot is associated with, or null for physical slot.
#       active (GAUGE)
#           True(1) if this slot is currently actively being used
#       temporary (GAUGE)
#           True(1) if this is a temporary replication slot.
#       xmin (COUNTER)
#           The oldest transaction that this slot needs the database to retain.
#       catalog_xmin (COUNTER)
#           The oldest transaction affecting the system catalogs that this slot needs the database to retain.
#       restart_lsn (COUNTER)
#           The address (LSN) of oldest WAL which still might be required by the consumer of this slot
#       confirm_lsn (COUNTER)
#           The address (LSN) up to which the logical slot's consumer has confirmed receiving data.
#       retained_bytes (GAUGE)
#           Size of bytes that retained for this slot
#       safe_wal_size (GAUGE)
#           bytes that can be written to WAL which will not make slot into lost
#       wal_status (GAUGE)
#           WAL reserve status 0-3 means reserved,extended,unreserved,lost, -1 means other
#
pg_slot_13:
    name: pg_slot
    desc: PostgreSQL replication slot metrics v13 (wal safe size and status)
    query: |
        SELECT slot_name, database AS datname,active,temporary,xmin::TEXT::BIGINT AS xmin,catalog_xmin::TEXT::BIGINT  AS catalog_xmin,
            restart_lsn - '0/0' AS restart_lsn, confirmed_flush_lsn - '0/0' AS confirm_lsn,
            CASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retained_bytes,
            safe_wal_size, CASE wal_status WHEN 'reserved' THEN 0 WHEN 'extended' THEN 1 WHEN 'unreserved' THEN 2 WHEN 'lost' THEN 3 ELSE -1 END AS wal_status
        FROM pg_replication_slots;
    tags:
        - cluster
        - primary
    ttl: 10
    timeout: 0.1
    min_version: 130000
    max_version: 140000
    fatal: false
    skip: false
    metrics:
        - slot_name:
            name: slot_name
            usage: LABEL
            description: A unique, cluster-wide identifier for the replication slot
        - datname:
            name: datname
            usage: LABEL
            description: The name of the database this slot is associated with, or null for physical slot.
        - active:
            name: active
            usage: GAUGE
            description: True(1) if this slot is currently actively being used
        - temporary:
            name: temporary
            usage: GAUGE
            description: True(1) if this is a temporary replication slot.
        - xmin:
            name: xmin
            usage: COUNTER
            description: The oldest transaction that this slot needs the database to retain.
        - catalog_xmin:
            name: catalog_xmin
            usage: COUNTER
            description: The oldest transaction affecting the system catalogs that this slot needs the database to retain.
        - restart_lsn:
            name: restart_lsn
            usage: COUNTER
            description: The address (LSN) of oldest WAL which still might be required by the consumer of this slot
        - confirm_lsn:
            name: confirm_lsn
            usage: COUNTER
            description: The address (LSN) up to which the logical slot's consumer has confirmed receiving data.
        - retained_bytes:
            name: retained_bytes
            usage: GAUGE
            description: Size of bytes that retained for this slot
        - safe_wal_size:
            name: safe_wal_size
            usage: GAUGE
            description: bytes that can be written to WAL which will not make slot into lost
        - wal_status:
            name: wal_status
            usage: GAUGE
            description: WAL reserve status 0-3 means reserved,extended,unreserved,lost, -1 means other

##
# SYNNOPSIS
#       pg_slot.pg_slot_10_12_*
#
# DESCRIPTION
#       PostgreSQL replication slot metrics v10 v11 v12
#
# OPTIONS
#       Tags       [cluster, primary]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    100000 ~ 130000
#       Source     240-pg_slot.yml
#
# METRICS
#       slot_name (LABEL)
#           A unique, cluster-wide identifier for the replication slot
#       datname (LABEL)
#           The name of the database this slot is associated with, or null for physical slot.
#       active (GAUGE)
#           True(1) if this slot is currently actively being used
#       temporary (GAUGE)
#           True(1) if this is a temporary replication slot.
#       xmin (COUNTER)
#           The oldest transaction that this slot needs the database to retain.
#       catalog_xmin (COUNTER)
#           The oldest transaction affecting the system catalogs that this slot needs the database to retain.
#       restart_lsn (COUNTER)
#           The address (LSN) of oldest WAL which still might be required by the consumer of this slot
#       confirm_lsn (COUNTER)
#           The address (LSN) up to which the logical slot's consumer has confirmed receiving data.
#       retained_bytes (GAUGE)
#           Size of bytes that retained for this slot
#
pg_slot_10_12:
    name: pg_slot
    desc: PostgreSQL replication slot metrics v10 v11 v12
    query: |
        SELECT slot_name, database AS datname,active,temporary,xmin::TEXT::BIGINT AS xmin,catalog_xmin::TEXT::BIGINT  AS catalog_xmin,
               restart_lsn - '0/0' AS restart_lsn, confirmed_flush_lsn - '0/0' AS confirm_lsn,
               CASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retained_bytes
        FROM pg_replication_slots;
    tags:
        - cluster
        - primary
    ttl: 10
    timeout: 0.1
    min_version: 100000
    max_version: 130000
    fatal: false
    skip: false
    metrics:
        - slot_name:
            name: slot_name
            usage: LABEL
            description: A unique, cluster-wide identifier for the replication slot
        - datname:
            name: datname
            usage: LABEL
            description: The name of the database this slot is associated with, or null for physical slot.
        - active:
            name: active
            usage: GAUGE
            description: True(1) if this slot is currently actively being used
        - temporary:
            name: temporary
            usage: GAUGE
            description: True(1) if this is a temporary replication slot.
        - xmin:
            name: xmin
            usage: COUNTER
            description: The oldest transaction that this slot needs the database to retain.
        - catalog_xmin:
            name: catalog_xmin
            usage: COUNTER
            description: The oldest transaction affecting the system catalogs that this slot needs the database to retain.
        - restart_lsn:
            name: restart_lsn
            usage: COUNTER
            description: The address (LSN) of oldest WAL which still might be required by the consumer of this slot
        - confirm_lsn:
            name: confirm_lsn
            usage: COUNTER
            description: The address (LSN) up to which the logical slot's consumer has confirmed receiving data.
        - retained_bytes:
            name: retained_bytes
            usage: GAUGE
            description: Size of bytes that retained for this slot


