##
# SYNNOPSIS
#       pg_recv.pg_recv_13_*
#
# DESCRIPTION
#       PostgreSQL walreceiver metrics 13+ (add written and flush lsn)
#
# OPTIONS
#       Tags       [cluster, replica]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    130000 ~ higher
#       Source     250-pg_recv.yml
#
# METRICS
#       sender_host (LABEL)
#           Host of the PostgreSQL instance this WAL receiver is connected to
#       sender_port (LABEL)
#           Port number of the PostgreSQL instance this WAL receiver is connected to.
#       slot_name (LABEL)
#           Replication slot name used by this WAL receiver
#       pid (GAUGE)
#           Process ID of the WAL receiver process
#       state (LABEL)
#           Encoded activity status of the WAL receiver process 0-4 for streaming|startup|catchup|backup|stopping
#       init_lsn (COUNTER)
#           First write-ahead log location used when WAL receiver is started
#       init_tli (COUNTER)
#           First timeline number used when WAL receiver is started
#       flush_lsn (COUNTER)
#           Last write-ahead log location already received and flushed to disk
#       write_lsn (COUNTER)
#           Last write-ahead log location already received and written to disk, but not flushed.
#       flush_tli (COUNTER)
#           Timeline number of last write-ahead log location received and flushed to disk
#       reported_lsn (COUNTER)
#           Last write-ahead log location reported to origin WAL sender
#       msg_send_time (GAUGE)
#           Send time of last message received from origin WAL sender
#       msg_recv_time (GAUGE)
#           Receipt time of last message received from origin WAL sender
#       reported_time (GAUGE)
#           Time of last write-ahead log location reported to origin WAL sender
#       time (GAUGE)
#           Time of current snapshot
#
pg_recv_13:
    name: pg_recv
    desc: PostgreSQL walreceiver metrics 13+ (add written and flush lsn)
    query: |
        SELECT coalesce(sender_host, (regexp_match(conninfo, '.*host=(\S+).*'))[1]) AS sender_host, coalesce(sender_port::TEXT, (regexp_match(conninfo, '.*port=(\S+).*'))[1]) AS sender_port, slot_name,
               pid, CASE status WHEN 'streaming' THEN 0 WHEN 'startup' THEN 1 WHEN 'catchup' THEN 2 WHEN 'backup' THEN 3 WHEN 'stopping' THEN 4 ELSE -1 END AS state,
               receive_start_lsn - '0/0' AS init_lsn,receive_start_tli AS init_tli,
               flushed_lsn - '0/0' AS flush_lsn,written_lsn - '0/0'AS write_lsn, received_tli AS flush_tli, latest_end_lsn - '0/0' AS reported_lsn,
               last_msg_send_time AS msg_send_time,last_msg_receipt_time AS msg_recv_time,latest_end_time AS reported_time,now() AS time FROM pg_stat_wal_receiver;
    tags:
        - cluster
        - replica
    ttl: 10
    timeout: 0.1
    min_version: 130000
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - sender_host:
            name: sender_host
            usage: LABEL
            description: Host of the PostgreSQL instance this WAL receiver is connected to
        - sender_port:
            name: sender_port
            usage: LABEL
            description: Port number of the PostgreSQL instance this WAL receiver is connected to.
        - slot_name:
            name: slot_name
            usage: LABEL
            description: Replication slot name used by this WAL receiver
        - pid:
            name: pid
            usage: GAUGE
            description: Process ID of the WAL receiver process
        - state:
            name: state
            usage: LABEL
            description: Encoded activity status of the WAL receiver process 0-4 for streaming|startup|catchup|backup|stopping
        - init_lsn:
            name: init_lsn
            usage: COUNTER
            description: First write-ahead log location used when WAL receiver is started
        - init_tli:
            name: init_tli
            usage: COUNTER
            description: First timeline number used when WAL receiver is started
        - flush_lsn:
            name: flush_lsn
            usage: COUNTER
            description: Last write-ahead log location already received and flushed to disk
        - write_lsn:
            name: write_lsn
            usage: COUNTER
            description: Last write-ahead log location already received and written to disk, but not flushed.
        - flush_tli:
            name: flush_tli
            usage: COUNTER
            description: Timeline number of last write-ahead log location received and flushed to disk
        - reported_lsn:
            name: reported_lsn
            usage: COUNTER
            description: Last write-ahead log location reported to origin WAL sender
        - msg_send_time:
            name: msg_send_time
            usage: GAUGE
            description: Send time of last message received from origin WAL sender
        - msg_recv_time:
            name: msg_recv_time
            usage: GAUGE
            description: Receipt time of last message received from origin WAL sender
        - reported_time:
            name: reported_time
            usage: GAUGE
            description: Time of last write-ahead log location reported to origin WAL sender
        - time:
            name: time
            usage: GAUGE
            description: Time of current snapshot

##
# SYNNOPSIS
#       pg_recv.pg_recv_11_*
#
# DESCRIPTION
#       PostgreSQL walreceiver metrics v11 v12 (add sender host and port)
#
# OPTIONS
#       Tags       [cluster, replica]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    110000 ~ 130000
#       Source     250-pg_recv.yml
#
# METRICS
#       sender_host (LABEL)
#           Host of the PostgreSQL instance this WAL receiver is connected to
#       sender_port (LABEL)
#           Port number of the PostgreSQL instance this WAL receiver is connected to.
#       slot_name (LABEL)
#           Replication slot name used by this WAL receiver
#       pid (GAUGE)
#           Process ID of the WAL receiver process
#       state (LABEL)
#           Encoded activity status of the WAL receiver process 0-4 for streaming|startup|catchup|backup|stopping
#       init_lsn (COUNTER)
#           First write-ahead log location used when WAL receiver is started
#       init_tli (COUNTER)
#           First timeline number used when WAL receiver is started
#       flush_lsn (COUNTER)
#           Last write-ahead log location already received and flushed to disk
#       flush_tli (COUNTER)
#           Timeline number of last write-ahead log location received and flushed to disk
#       reported_lsn (COUNTER)
#           Last write-ahead log location reported to origin WAL sender
#       msg_send_time (GAUGE)
#           Send time of last message received from origin WAL sender
#       msg_recv_time (GAUGE)
#           Receipt time of last message received from origin WAL sender
#       reported_time (GAUGE)
#           Time of last write-ahead log location reported to origin WAL sender
#       time (GAUGE)
#           Time of current snapshot
#
pg_recv_11:
    name: pg_recv
    desc: PostgreSQL walreceiver metrics v11 v12 (add sender host and port)
    query: |
        SELECT coalesce(sender_host, (regexp_match(conninfo, '.*host=(\S+).*'))[1]) AS sender_host, coalesce(sender_port::TEXT, (regexp_match(conninfo, '.*port=(\S+).*'))[1]) AS sender_port, slot_name,
               pid, CASE status WHEN 'streaming' THEN 0 WHEN 'startup' THEN 1 WHEN 'catchup' THEN 2 WHEN 'backup' THEN 3 WHEN 'stopping' THEN 4 ELSE -1 END AS state,
               receive_start_lsn - '0/0' AS init_lsn,receive_start_tli AS init_tli,
               received_lsn - '0/0' AS flush_lsn, received_tli AS flush_tli, latest_end_lsn - '0/0' AS reported_lsn,
               last_msg_send_time AS msg_send_time,last_msg_receipt_time AS msg_recv_time,latest_end_time AS reported_time,now() AS time FROM pg_stat_wal_receiver;
    tags:
        - cluster
        - replica
    ttl: 10
    timeout: 0.1
    min_version: 110000
    max_version: 130000
    fatal: false
    skip: false
    metrics:
        - sender_host:
            name: sender_host
            usage: LABEL
            description: Host of the PostgreSQL instance this WAL receiver is connected to
        - sender_port:
            name: sender_port
            usage: LABEL
            description: Port number of the PostgreSQL instance this WAL receiver is connected to.
        - slot_name:
            name: slot_name
            usage: LABEL
            description: Replication slot name used by this WAL receiver
        - pid:
            name: pid
            usage: GAUGE
            description: Process ID of the WAL receiver process
        - state:
            name: state
            usage: LABEL
            description: Encoded activity status of the WAL receiver process 0-4 for streaming|startup|catchup|backup|stopping
        - init_lsn:
            name: init_lsn
            usage: COUNTER
            description: First write-ahead log location used when WAL receiver is started
        - init_tli:
            name: init_tli
            usage: COUNTER
            description: First timeline number used when WAL receiver is started
        - flush_lsn:
            name: flush_lsn
            usage: COUNTER
            description: Last write-ahead log location already received and flushed to disk
        - flush_tli:
            name: flush_tli
            usage: COUNTER
            description: Timeline number of last write-ahead log location received and flushed to disk
        - reported_lsn:
            name: reported_lsn
            usage: COUNTER
            description: Last write-ahead log location reported to origin WAL sender
        - msg_send_time:
            name: msg_send_time
            usage: GAUGE
            description: Send time of last message received from origin WAL sender
        - msg_recv_time:
            name: msg_recv_time
            usage: GAUGE
            description: Receipt time of last message received from origin WAL sender
        - reported_time:
            name: reported_time
            usage: GAUGE
            description: Time of last write-ahead log location reported to origin WAL sender
        - time:
            name: time
            usage: GAUGE
            description: Time of current snapshot

##
# SYNNOPSIS
#       pg_recv.pg_recv_10_*
#
# DESCRIPTION
#       PostgreSQL walreceiver metrics v10 (v9.6)
#
# OPTIONS
#       Tags       [cluster, replica]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90600 ~ 110000
#       Source     250-pg_recv.yml
#
# METRICS
#       sender_host (LABEL)
#           Host of the PostgreSQL instance this WAL receiver is connected to
#       sender_port (LABEL)
#           Port number of the PostgreSQL instance this WAL receiver is connected to.
#       slot_name (LABEL)
#           Replication slot name used by this WAL receiver
#       pid (GAUGE)
#           Process ID of the WAL receiver process
#       state (LABEL)
#           Encoded activity status of the WAL receiver process 0-4 for streaming|startup|catchup|backup|stopping
#       init_lsn (COUNTER)
#           First write-ahead log location used when WAL receiver is started
#       init_tli (COUNTER)
#           First timeline number used when WAL receiver is started
#       flush_lsn (COUNTER)
#           Last write-ahead log location already received and flushed to disk
#       flush_tli (COUNTER)
#           Timeline number of last write-ahead log location received and flushed to disk
#       reported_lsn (COUNTER)
#           Last write-ahead log location reported to origin WAL sender
#       msg_send_time (GAUGE)
#           Send time of last message received from origin WAL sender
#       msg_recv_time (GAUGE)
#           Receipt time of last message received from origin WAL sender
#       reported_time (GAUGE)
#           Time of last write-ahead log location reported to origin WAL sender
#       time (GAUGE)
#           Time of current snapshot
#
pg_recv_10:
    name: pg_recv
    desc: PostgreSQL walreceiver metrics v10 (v9.6)
    query: |
        SELECT (regexp_match(conninfo, '.*host=(\S+).*'))[1] AS sender_host, (regexp_match(conninfo, '.*port=(\S+).*'))[1] AS sender_port, slot_name,
               pid, CASE status WHEN 'streaming' THEN 0 WHEN 'startup' THEN 1 WHEN 'catchup' THEN 2 WHEN 'backup' THEN 3 WHEN 'stopping' THEN 4 ELSE -1 END AS state,
               receive_start_lsn - '0/0' AS init_lsn,receive_start_tli AS init_tli,
               received_lsn - '0/0' AS flush_lsn, received_tli AS flush_tli, latest_end_lsn - '0/0' AS reported_lsn,
               last_msg_send_time AS msg_send_time,last_msg_receipt_time AS msg_recv_time,latest_end_time AS reported_time,now() AS time FROM pg_stat_wal_receiver;
    tags:
        - cluster
        - replica
    ttl: 10
    timeout: 0.1
    min_version: 90600
    max_version: 110000
    fatal: false
    skip: false
    metrics:
        - sender_host:
            name: sender_host
            usage: LABEL
            description: Host of the PostgreSQL instance this WAL receiver is connected to
        - sender_port:
            name: sender_port
            usage: LABEL
            description: Port number of the PostgreSQL instance this WAL receiver is connected to.
        - slot_name:
            name: slot_name
            usage: LABEL
            description: Replication slot name used by this WAL receiver
        - pid:
            name: pid
            usage: GAUGE
            description: Process ID of the WAL receiver process
        - state:
            name: state
            usage: LABEL
            description: Encoded activity status of the WAL receiver process 0-4 for streaming|startup|catchup|backup|stopping
        - init_lsn:
            name: init_lsn
            usage: COUNTER
            description: First write-ahead log location used when WAL receiver is started
        - init_tli:
            name: init_tli
            usage: COUNTER
            description: First timeline number used when WAL receiver is started
        - flush_lsn:
            name: flush_lsn
            usage: COUNTER
            description: Last write-ahead log location already received and flushed to disk
        - flush_tli:
            name: flush_tli
            usage: COUNTER
            description: Timeline number of last write-ahead log location received and flushed to disk
        - reported_lsn:
            name: reported_lsn
            usage: COUNTER
            description: Last write-ahead log location reported to origin WAL sender
        - msg_send_time:
            name: msg_send_time
            usage: GAUGE
            description: Send time of last message received from origin WAL sender
        - msg_recv_time:
            name: msg_recv_time
            usage: GAUGE
            description: Receipt time of last message received from origin WAL sender
        - reported_time:
            name: reported_time
            usage: GAUGE
            description: Time of last write-ahead log location reported to origin WAL sender
        - time:
            name: time
            usage: GAUGE
            description: Time of current snapshot


