##
# SYNNOPSIS
#       pg_sub.pg_sub_10_*
#
# DESCRIPTION
#       PostgreSQL subscription statistics ()
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    100000 ~ higher
#       Source     260-pg_sub.yml
#
# METRICS
#       subname (LABEL)
#           Name of this subscription
#       id (GAUGE)
#           OID of the subscription
#       pid (GAUGE)
#           Process ID of the subscription main apply worker process
#       received_lsn (COUNTER)
#           Last write-ahead log location received
#       reported_lsn (COUNTER)
#           Last write-ahead log location reported to origin WAL sender
#       msg_send_time (GAUGE)
#           Send time of last message received from origin WAL sender
#       msg_recv_time (GAUGE)
#           Receipt time of last message received from origin WAL sender
#       reported_time (GAUGE)
#           Time of last write-ahead log location reported to origin WAL sender
#
pg_sub_10:
    name: pg_sub
    desc: PostgreSQL subscription statistics ()
    query: |
        SELECT subname, subid AS id, pid,
               received_lsn - '0/0' AS received_lsn, latest_end_lsn - '0/0' AS reported_lsn,
               extract(epoch from last_msg_send_time) AS msg_send_time,
               extract(epoch from last_msg_receipt_time) AS msg_recv_time,
               extract(epoch from latest_end_time) AS reported_time
        FROM pg_stat_subscription WHERE relid ISNULL;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 100000
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - subname:
            name: subname
            usage: LABEL
            description: Name of this subscription
        - id:
            name: id
            usage: GAUGE
            description: OID of the subscription
        - pid:
            name: pid
            usage: GAUGE
            description: Process ID of the subscription main apply worker process
        - received_lsn:
            name: received_lsn
            usage: COUNTER
            description: Last write-ahead log location received
        - reported_lsn:
            name: reported_lsn
            usage: COUNTER
            description: Last write-ahead log location reported to origin WAL sender
        - msg_send_time:
            name: msg_send_time
            usage: GAUGE
            description: Send time of last message received from origin WAL sender
        - msg_recv_time:
            name: msg_recv_time
            usage: GAUGE
            description: Receipt time of last message received from origin WAL sender
        - reported_time:
            name: reported_time
            usage: GAUGE
            description: Time of last write-ahead log location reported to origin WAL sender


