##
# SYNNOPSIS
#       pg_origin_*
#
# DESCRIPTION
#       PostgreSQL replay state (approximate) for a certain origin
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90500 ~ higher
#       Source     270-pg_origin.yml
#
# METRICS
#       roiname (LABEL)
#           The external, user defined, name of a replication origin.
#       remote_lsn (LABEL)
#           The origin node's LSN up to which data has been replicated.
#       local_lsn (LABEL)
#           This node's LSN at which remote_lsn has been replicated.
#
pg_origin:
    name: pg_origin
    desc: PostgreSQL replay state (approximate) for a certain origin
    query: SELECT roname, remote_lsn - '0/0' AS remote_lsn, local_lsn - '0/0' AS local_lsn FROM pg_replication_origin o LEFT JOIN pg_replication_origin_status os ON o.roident = os.local_id;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 90500
    max_version: 0
    fatal: false
    skip: true
    metrics:
        - roiname:
            name: roiname
            usage: LABEL
            description: The external, user defined, name of a replication origin.
        - remote_lsn:
            name: remote_lsn
            usage: LABEL
            description: The origin node's LSN up to which data has been replicated.
        - local_lsn:
            name: local_lsn
            usage: LABEL
            description: This node's LSN at which remote_lsn has been replicated.


