##
# SYNNOPSIS
#       pg_archiver_*
#
# DESCRIPTION
#       PostgreSQL archiver process statistics
#
# OPTIONS
#       Tags       [cluster]
#       TTL        60
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90400 ~ higher
#       Source     320-pg_archiver.yml
#
# METRICS
#       finish_count (COUNTER)
#           Number of WAL files that have been successfully archived
#       failed_count (COUNTER)
#           Number of failed attempts for archiving WAL files
#       last_finish_time (COUNTER)
#           Time of the last successful archive operation
#       last_failed_time (COUNTER)
#           Time of the last failed archival operation
#       reset_time (GAUGE)
#           Time at which archive statistics were last reset
#
pg_archiver:
    name: pg_archiver
    desc: PostgreSQL archiver process statistics
    query: SELECT archived_count AS finish_count, failed_count, last_archived_time AS last_finish_time, last_failed_time, extract(EPOCH FROM stats_reset) AS reset_time FROM pg_stat_archiver;
    tags:
        - cluster
    ttl: 60
    timeout: 0.1
    min_version: 90400
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - finish_count:
            name: finish_count
            usage: COUNTER
            description: Number of WAL files that have been successfully archived
        - failed_count:
            name: failed_count
            usage: COUNTER
            description: Number of failed attempts for archiving WAL files
        - last_finish_time:
            name: last_finish_time
            usage: COUNTER
            description: Time of the last successful archive operation
        - last_failed_time:
            name: last_failed_time
            usage: COUNTER
            description: Time of the last failed archival operation
        - reset_time:
            name: reset_time
            usage: GAUGE
            description: Time at which archive statistics were last reset


