##
# SYNNOPSIS
#       pg_bgwriter_*
#
# DESCRIPTION
#       PostgreSQL background writer metrics
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90400 ~ higher
#       Source     330-pg_bgwriter.yml
#
# METRICS
#       checkpoints_timed (COUNTER)
#           Number of scheduled checkpoints that have been performed
#       checkpoints_req (COUNTER)
#           Number of requested checkpoints that have been performed
#       checkpoint_write_time (COUNTER)
#           Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk, in seconds
#       checkpoint_sync_time (COUNTER)
#           Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk, in seconds
#       buffers_checkpoint (COUNTER)
#           Number of buffers written during checkpoints
#       buffers_clean (COUNTER)
#           Number of buffers written by the background writer
#       buffers_backend (COUNTER)
#           Number of buffers written directly by a backend
#       maxwritten_clean (COUNTER)
#           Number of times the background writer stopped a cleaning scan because it had written too many buffers
#       buffers_backend_fsync (COUNTER)
#           Number of times a backend had to execute its own fsync call
#       buffers_alloc (COUNTER)
#           Number of buffers allocated
#       reset_time (COUNTER)
#           Time at which bgwriter statistics were last reset
#
pg_bgwriter:
    name: pg_bgwriter
    desc: PostgreSQL background writer metrics
    query: SELECT checkpoints_timed, checkpoints_req, checkpoint_write_time, checkpoint_sync_time, buffers_checkpoint, buffers_clean, buffers_backend, maxwritten_clean, buffers_backend_fsync, buffers_alloc, extract(EPOCH FROM stats_reset) AS reset_time FROM pg_stat_bgwriter;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 90400
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - checkpoints_timed:
            name: checkpoints_timed
            usage: COUNTER
            description: Number of scheduled checkpoints that have been performed
        - checkpoints_req:
            name: checkpoints_req
            usage: COUNTER
            description: Number of requested checkpoints that have been performed
        - checkpoint_write_time:
            name: checkpoint_write_time
            usage: COUNTER
            scale: "1e-3"
            description: Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk, in seconds
        - checkpoint_sync_time:
            name: checkpoint_sync_time
            usage: COUNTER
            scale: "1e-3"
            description: Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk, in seconds
        - buffers_checkpoint:
            name: buffers_checkpoint
            usage: COUNTER
            description: Number of buffers written during checkpoints
        - buffers_clean:
            name: buffers_clean
            usage: COUNTER
            description: Number of buffers written by the background writer
        - buffers_backend:
            name: buffers_backend
            usage: COUNTER
            description: Number of buffers written directly by a backend
        - maxwritten_clean:
            name: maxwritten_clean
            usage: COUNTER
            description: Number of times the background writer stopped a cleaning scan because it had written too many buffers
        - buffers_backend_fsync:
            name: buffers_backend_fsync
            usage: COUNTER
            description: Number of times a backend had to execute its own fsync call
        - buffers_alloc:
            name: buffers_alloc
            usage: COUNTER
            description: Number of buffers allocated
        - reset_time:
            name: reset_time
            usage: COUNTER
            description: Time at which bgwriter statistics were last reset


