##
# SYNNOPSIS
#       pg_ssl_*
#
# DESCRIPTION
#       PostgreSQL SSL client conenction count
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90500 ~ higher
#       Source     340-pg_ssl.yml
#
# METRICS
#       enabled (GAUGE)
#           Number of client connection that use ssl
#       disabled (GAUGE)
#           Number of client connection that does not use ssl
#
pg_ssl:
    name: pg_ssl
    desc: PostgreSQL SSL client conenction count
    query: |
        SELECT count(*) FILTER (WHERE ssl) AS enabled, count(*) FILTER ( WHERE NOT ssl) AS disabled FROM pg_stat_ssl;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 90500
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - enabled:
            name: enabled
            usage: GAUGE
            description: Number of client connection that use ssl
        - disabled:
            name: disabled
            usage: GAUGE
            description: Number of client connection that does not use ssl


