##
# SYNNOPSIS
#       pg_shmem_*
#
# DESCRIPTION
#       Allocations made from the server's main shared memory segment
#
# OPTIONS
#       Tags       [cluster, schema:monitor]
#       TTL        60
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    130000 ~ higher
#       Source     380-pg_shmem.yml
#
# METRICS
#       name (LABEL)
#           Name of the shared memory allocation
#       offset (GAUGE)
#           The offset at which the allocation starts
#       size (GAUGE)
#           Size of the allocation
#       allocated_size (GAUGE)
#           Size of the allocation including padding
#
pg_shmem:
    name: pg_shmem
    desc: Allocations made from the server's main shared memory segment
    query: SELECT coalesce(name, 'Free') AS name, off AS offset, size, allocated_size FROM monitor.pg_shmem();
    tags:
        - cluster
        - schema:monitor
    ttl: 60
    timeout: 0.1
    min_version: 130000
    max_version: 0
    fatal: false
    skip: true
    metrics:
        - name:
            name: name
            usage: LABEL
            description: Name of the shared memory allocation
        - offset:
            name: offset
            usage: GAUGE
            description: The offset at which the allocation starts
        - size:
            name: size
            usage: GAUGE
            description: Size of the allocation
        - allocated_size:
            name: allocated_size
            usage: GAUGE
            description: Size of the allocation including padding


