##
# SYNNOPSIS
#       pg_backend_*
#
# DESCRIPTION
#       PostgreSQL backend client count group by wait event type since 9.6
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90600 ~ higher
#       Source     430-pg_backend.yml
#
# METRICS
#       type (LABEL)
#           Database backend process type
#       count (GAUGE)
#           Database backend process count by backend_type
#
pg_backend:
    name: pg_backend
    desc: PostgreSQL backend client count group by wait event type since 9.6
    query: SELECT backend_type AS "type", count(*) AS count FROM pg_stat_activity GROUP BY backend_type;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 90600
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - type:
            name: type
            usage: LABEL
            description: Database backend process type
        - count:
            name: count
            usage: GAUGE
            description: Database backend process count by backend_type


