##
# SYNNOPSIS
#       pg_vacuuming_*
#
# DESCRIPTION
#       PostgreSQL vacuum progress since 9.6
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    120000 ~ higher
#       Source     510-pg_vacuuming.yml
#
# METRICS
#       datname (LABEL)
#           database name
#       pid (LABEL)
#           process id of indexing table
#       relname (LABEL)
#           relation name of indexed table
#       progress (GAUGE)
#           the actual progress
#
pg_vacuuming:
    name: pg_vacuuming
    desc: PostgreSQL vacuum progress since 9.6
    query: |
        SELECT datname, pid, relid::RegClass AS relname,
            CASE phase WHEN 'scanning heap' THEN (CASE WHEN heap_blks_total > 0 THEN 1.0 * heap_blks_scanned / heap_blks_total ELSE 0.0 END)
            WHEN 'vacuuming heap' THEN (CASE WHEN heap_blks_total > 0 THEN 1.0 * heap_blks_vacuumed / heap_blks_total ELSE 0 END)
            ELSE NULL END AS progress FROM pg_stat_progress_vacuum pspv;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 120000
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - datname:
            name: datname
            usage: LABEL
            description: database name
        - pid:
            name: pid
            usage: LABEL
            description: process id of indexing table
        - relname:
            name: relname
            usage: LABEL
            description: relation name of indexed table
        - progress:
            name: progress
            usage: GAUGE
            description: the actual progress


