##
# SYNNOPSIS
#       pg_clustering_*
#
# DESCRIPTION
#       PostgreSQL cluster or vacuum full progress (v12+)
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    120000 ~ higher
#       Source     530-pg_clustering.yml
#
# METRICS
#       datname (LABEL)
#           Name of databae been clustering
#       pid (LABEL)
#           Process id of indexing table
#       relname (LABEL)
#           Relation name of indexed table
#       tup_scan (GAUGE)
#           How much tuple been scanned
#       progress (GAUGE)
#           Progress of heap been processed
#
pg_clustering:
    name: pg_clustering
    desc: PostgreSQL cluster or vacuum full progress (v12+)
    query: SELECT datname, pid, relid::RegClass AS relname, param4 AS tup_scan, CASE WHEN param6 > 0 THEN 1.0 * param7 / param6 ELSE 0 END AS progress FROM pg_stat_get_progress_info('cluster') s LEFT JOIN pg_database d ON s.datid = d.oid;;
    tags:
        - cluster
    ttl: 10
    timeout: 0.1
    min_version: 120000
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - datname:
            name: datname
            usage: LABEL
            description: Name of databae been clustering
        - pid:
            name: pid
            usage: LABEL
            description: Process id of indexing table
        - relname:
            name: relname
            usage: LABEL
            description: Relation name of indexed table
        - tup_scan:
            name: tup_scan
            usage: GAUGE
            description: How much tuple been scanned
        - progress:
            name: progress
            usage: GAUGE
            description: Progress of heap been processed


