##
# SYNNOPSIS
#       pg_pubrel_*
#
# DESCRIPTION
#       PostgreSQL publication and relation count
#
# OPTIONS
#       Tags       []
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    100000 ~ higher
#       Source     640-pg_pubrel.yml
#
# METRICS
#       datname (LABEL)
#           Name of the database which publication belonged
#       pubname (LABEL)
#           Name of the publication
#       count (GAUGE)
#           Count of relation in the publication
#
pg_pubrel:
    name: pg_pubrel
    desc: PostgreSQL publication and relation count
    query: SELECT CURRENT_CATALOG AS datname, pubname, count(*) AS count FROM pg_publication p, LATERAL pg_get_publication_tables(pubname) GROUP BY pubname;
    tags: []
    ttl: 10
    timeout: 0.1
    min_version: 100000
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - datname:
            name: datname
            usage: LABEL
            description: Name of the database which publication belonged
        - pubname:
            name: pubname
            usage: LABEL
            description: Name of the publication
        - count:
            name: count
            usage: GAUGE
            description: Count of relation in the publication


