##
# SYNNOPSIS
#       pg_subrel_*
#
# DESCRIPTION
#       PostgreSQL subscripted relation group by state
#
# OPTIONS
#       Tags       []
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    100000 ~ higher
#       Source     650-pg_subrel.yml
#
# METRICS
#       datname (LABEL)
#           Name of the database which publication belonged
#       subname (LABEL)
#           Name of the subscription
#       state (LABEL)
#           State of table in subscription, i=initialize, d=data copy, s=sync, r=ready
#       count (GAUGE)
#           Count of relation in this subscription and corresponding state
#
pg_subrel:
    name: pg_subrel
    desc: PostgreSQL subscripted relation group by state
    query: SELECT CURRENT_CATALOG AS datname, subname, srsubstate::TEXT AS state, count(*) AS count FROM pg_subscription_rel sr LEFT JOIN pg_stat_subscription  ss ON sr.srsubid = ss.subid GROUP BY 2, 3;
    tags: []
    ttl: 10
    timeout: 0.1
    min_version: 100000
    max_version: 0
    fatal: false
    skip: false
    metrics:
        - datname:
            name: datname
            usage: LABEL
            description: Name of the database which publication belonged
        - subname:
            name: subname
            usage: LABEL
            description: Name of the subscription
        - state:
            name: state
            usage: LABEL
            description: State of table in subscription, i=initialize, d=data copy, s=sync, r=ready
        - count:
            name: count
            usage: GAUGE
            description: Count of relation in this subscription and corresponding state


