
###############################################################
#                  Per Database Collectors                    #
###############################################################


pg_class:
  name: pg_class
  desc: Postgres relation catalog info db level normal version
  query: |
    SELECT CURRENT_CATALOG AS datname,relnamespace::RegNamespace || '.' || relname AS relname, relkind,relpages,reltuples,CASE WHEN relkind = 'i' THEN NULL ELSE age(relfrozenxid) END AS relage,pg_relation_size(oid) AS relsize,relnatts FROM pg_class c
        WHERE relnamespace = ANY(SELECT oid FROM pg_namespace WHERE nspname <> ALL(ARRAY['pg_catalog','information_schema','pg_toast','columnar']) AND nspname !~'timescaledb' AND nspname !~'citus') AND relkind = ANY(ARRAY['r', 'i', 'm', 't']) ORDER BY relpages DESC LIMIT 256;
  ttl: 60
  timeout: 1
  min_version: 090400

  metrics:
    - datname:
        usage: LABEL
        description: Database name of this relation
    - relname:
        usage: LABEL
        description: Full qualified name of this relation
    - relkind:
        usage: LABEL
        description: Relation kind r-table i-index s-sequence m-mview t-toast
    - relpages:
        usage: GAUGE
        description: Size of the on-disk representation of this table in pages
        # Size of the on-disk representation of this table in pages (of size BLCKSZ). This is only an estimate used by the planner. It is updated by VACUUM, ANALYZE, and a few DDL commands such as CREATE INDEX.
    - reltuples:
        usage: GAUGE
        description: Estimate relation tuples
    - relage:
        usage: GAUGE
        description: Age of non-index relation from relfrozenxid
    - relsize:
        usage: GAUGE
        description: Relation size
    - relnatts:
        usage: GAUGE
        description: Number of user columns in the relation
