##
# SYNNOPSIS
#       pg_index_bloat_*
#
# DESCRIPTION
#       PostgreSQL index bloat metrics (btree only), require monitor.pg_index_bloat
#
# OPTIONS
#       Tags       [schema:monitor]
#       TTL        300
#       Priority   0
#       Timeout    2s
#       Fatal      false
#       Version    90400 ~ higher
#       Source     830-pg_index_bloat.yml
#
# METRICS
#       datname (LABEL)
#           Database name of this index
#       relname (LABEL)
#           Schema qualified index name
#       size (GAUGE)
#           Total bytes of this index
#       ratio (GAUGE)
#           Estimated bloat ratio of this index, 0~1
#
pg_index_bloat:
    name: pg_index_bloat
    desc: PostgreSQL index bloat metrics (btree only), require monitor.pg_index_bloat
    query: SELECT datname, nspname || '.' || relname AS relname, size, ratio FROM monitor.pg_index_bloat ORDER BY size DESC LIMIT 64;
    tags:
        - schema:monitor
    ttl: 300
    timeout: 2
    min_version: 90400
    max_version: 0
    fatal: false
    skip: true
    metrics:
        - datname:
            name: datname
            usage: LABEL
            description: Database name of this index
        - relname:
            name: relname
            usage: LABEL
            description: Schema qualified index name
        - size:
            name: size
            usage: GAUGE
            description: Total bytes of this index
        - ratio:
            name: ratio
            usage: GAUGE
            description: Estimated bloat ratio of this index, 0~1


