##
# SYNOPSIS
#       pgbouncer_stat_*
#
# DESCRIPTION
#       Pgbouncer stats per database
#
# OPTIONS
#       Tags       [pgbouncer]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    10800 ~ higher
#       Source     930-pgbouncer_stat.yml
#
# METRICS
#       database (LABEL)
#           Name of database
#       total_xact_count (GAUGE)
#           Total number of SQL transactions pooled by pgbouncer
#       total_query_count (GAUGE)
#           Total number of SQL queries pooled by pgbouncer
#       total_received (COUNTER)
#           Total volume in bytes of network traffic received by pgbouncer
#       total_sent (COUNTER)
#           Total volume in bytes of network traffic sent by pgbouncer
#       total_xact_time (COUNTER)
#           Total number of seconds spent when in a transaction
#       total_query_time (COUNTER)
#           Total number of seconds spent when executing queries
#       total_wait_time (COUNTER)
#           Time spent by clients waiting for a server, in seconds
#       avg_xact_count (GAUGE)
#           Average transactions per second in last stat period
#       avg_query_count (GAUGE)
#           Average queries per second in last stat period
#       avg_recv (GAUGE)
#           Average received (from clients) bytes per second
#       avg_sent (GAUGE)
#           Average sent (to clients) bytes per second
#       avg_xact_time (GAUGE)
#           Average transaction duration, in seconds
#       avg_query_time (GAUGE)
#           Average query duration, in seconds
#       avg_wait_time (GAUGE)
#           Time spent by clients waiting for a server, in seconds (average per second).
#
pgbouncer_stat:
  name: pgbouncer_stat
  desc: Pgbouncer stats per database   # http://www.pgbouncer.org/usage.html#show-stats
  query: SHOW STATS;
  ttl: 10
  min_version: 10800
  tags:
    - pgbouncer

  metrics:
    - database:
        usage: LABEL
        rename: datname
        description: Name of database
    - total_xact_count:
        usage: GAUGE
        description: Total number of SQL transactions pooled by pgbouncer
    - total_query_count:
        usage: GAUGE
        description: Total number of SQL queries pooled by pgbouncer
    - total_received:
        usage: COUNTER
        description: Total volume in bytes of network traffic received by pgbouncer
    - total_sent:
        usage: COUNTER
        description: Total volume in bytes of network traffic sent by pgbouncer
    - total_xact_time:
        usage: COUNTER
        scale: 1e-6
        description: Total number of seconds spent when in a transaction
    - total_query_time:
        usage: COUNTER
        scale: 1e-6
        description: Total number of seconds spent when executing queries
    - total_wait_time:
        usage: COUNTER
        scale: 1e-6
        description: Time spent by clients waiting for a server, in seconds
    - avg_xact_count:
        usage: GAUGE
        description: Average transactions per second in last stat period
    - avg_query_count:
        usage: GAUGE
        description: Average queries per second in last stat period
    - avg_recv:
        usage: GAUGE
        description: Average received (from clients) bytes per second
    - avg_sent:
        usage: GAUGE
        description: Average sent (to clients) bytes per second
    - avg_xact_time:
        usage: GAUGE
        scale: 1e-6
        description: Average transaction duration, in seconds
    - avg_query_time:
        usage: GAUGE
        scale: 1e-6
        description: Average query duration, in seconds
    - avg_wait_time:
        usage: GAUGE
        scale: 1e-6
        description: Time spent by clients waiting for a server, in seconds (average per second).

