
#┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#┃ pgbouncer_pool
#┃ pgbouncer pool stats: http://www.pgbouncer.org/usage.html#show-pools
#┣┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
#┃ pgbouncer_pool_active_clients{datname,user}   GAUGE    client connections that are linked to server connection and can process queries
#┃ pgbouncer_pool_waiting_clients{datname,user}  GAUGE    client connections that have sent queries but have not yet got a server connection
#┃ pgbouncer_pool_active_servers{datname,user}   GAUGE    server connections that are linked to a client
#┃ pgbouncer_pool_idle_servers{datname,user}     GAUGE    server connections that are unused and immediately usable for client queries
#┃ pgbouncer_pool_used_servers{datname,user}     GAUGE    server connections that have been idle for more than server_check_delay (means have to run check query)
#┃ pgbouncer_pool_tested_servers{datname,user}   GAUGE    server connections that are currently running reset or check query
#┃ pgbouncer_pool_login_servers{datname,user}    GAUGE    server connections currently in the process of logging in
#┃ pgbouncer_pool_maxwait{datname,user}          GAUGE    how long the first(oldest) client in the queue has waited, in seconds, key metric
#┃ pgbouncer_pool_maxwait_us{datname,user}       GAUGE    microsecond part of the maximum waiting time.
#┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
pgbouncer_pool_116:
  name: pgbouncer_pool
  desc: Pgbouncer pool stats (1.16+)    # http://www.pgbouncer.org/usage.html#show-pools
  query: SHOW POOLS;
  ttl: 10
  min_version: 11600
  tags:
    - pgbouncer

  metrics:
    - database:
        usage: LABEL
        rename: datname
        description: Database name of this pool
    - user:
        usage: LABEL
        description: User name of this pool
    - cl_active:
        usage: GAUGE
        rename: active_clients
        description: Client connections that are linked to server connection and can process queries
    - cl_waiting:
        usage: GAUGE
        rename: waiting_clients
        description: Client connections that have sent queries but have not yet got a server connection
    - cl_cancel_req:
        usage: GAUGE
        rename: cancel_clients
        description: Client connections that have not forwarded query cancellations to the server yet.
    - sv_active:
        usage: GAUGE
        rename: active_servers
        description: Server connections that are linked to a client
    - sv_idle:
        usage: GAUGE
        rename: idle_servers
        description: Server connections that are unused and immediately usable for client queries
    - sv_used:
        usage: GAUGE
        rename: used_servers
        description: Server connections that have been idle for more than server_check_delay (means have to run check query)
    - sv_tested:
        usage: GAUGE
        rename: tested_servers
        description: Server connections that are currently running reset or check query
    - sv_login:
        usage: GAUGE
        rename: login_servers
        description: Server connections currently in the process of logging in
    - maxwait:
        usage: GAUGE
        description: How long the first(oldest) client in the queue has waited, in seconds, key metric
    - maxwait_us:
        usage: GAUGE
        description: Microsecond part of the maximum waiting time.
    - pool_mode:
        usage: LABEL
        description: Pooling mode in use




pgbouncer_pool_108_115:
  name: pgbouncer_pool
  desc: Pgbouncer pool stats (1.08-1.15)   # http://www.pgbouncer.org/usage.html#show-pools
  query: SHOW POOLS;
  ttl: 10
  min_version: 10800
  max_version: 11600
  tags:
    - pgbouncer

  metrics:
    - database:
        usage: LABEL
        rename: datname
        description: Database name of this pool
    - user:
        usage: LABEL
        description: User name of this pool
    - cl_active:
        usage: GAUGE
        rename: active_clients
        description: Client connections that are linked to server connection and can process queries
    - cl_waiting:
        usage: GAUGE
        rename: waiting_clients
        description: Client connections that have sent queries but have not yet got a server connection
    - sv_active:
        usage: GAUGE
        rename: active_servers
        description: Server connections that are linked to a client
    - sv_idle:
        usage: GAUGE
        rename: idle_servers
        description: Server connections that are unused and immediately usable for client queries
    - sv_used:
        usage: GAUGE
        rename: used_servers
        description: Server connections that have been idle for more than server_check_delay (means have to run check query)
    - sv_tested:
        usage: GAUGE
        rename: tested_servers
        description: Server connections that are currently running reset or check query
    - sv_login:
        usage: GAUGE
        rename: login_servers
        description: Server connections currently in the process of logging in
    - maxwait:
        usage: GAUGE
        description: How long the first(oldest) client in the queue has waited, in seconds, key metric
    - maxwait_us:
        usage: GAUGE
        description: Microsecond part of the maximum waiting time.
    - pool_mode:
        usage: LABEL
        description: Pooling mode in use

